// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import HelloController from "./hello_controller"
application.register("hello", HelloController)

import RecaudosController from "./recaudos_controller"
application.register("recaudos", RecaudosController)

import SortableTableController from "./sortable_table_controller"
application.register("sortable-table", SortableTableController)

import EnrollmentController from "./enrollment_controller"
application.register("enrollment", EnrollmentController)
